/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as SignUpImport } from './routes/sign-up';
import { Route as LoginImport } from './routes/login';
import { Route as FirebasePlaygroundImport } from './routes/firebase-playground';
import { Route as IndexImport } from './routes/index';
import { Route as RoomsRoomIdImport } from './routes/rooms/$roomId';
import { Route as JoinRoomIdImport } from './routes/join/$roomId';

// Create/Update Routes

const SignUpRoute = SignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute
} as any);

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute
} as any);

const FirebasePlaygroundRoute = FirebasePlaygroundImport.update({
  id: '/firebase-playground',
  path: '/firebase-playground',
  getParentRoute: () => rootRoute
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute
} as any);

const RoomsRoomIdRoute = RoomsRoomIdImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRoute
} as any);

const JoinRoomIdRoute = JoinRoomIdImport.update({
  id: '/join/$roomId',
  path: '/join/$roomId',
  getParentRoute: () => rootRoute
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/firebase-playground': {
      id: '/firebase-playground';
      path: '/firebase-playground';
      fullPath: '/firebase-playground';
      preLoaderRoute: typeof FirebasePlaygroundImport;
      parentRoute: typeof rootRoute;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    '/sign-up': {
      id: '/sign-up';
      path: '/sign-up';
      fullPath: '/sign-up';
      preLoaderRoute: typeof SignUpImport;
      parentRoute: typeof rootRoute;
    };
    '/join/$roomId': {
      id: '/join/$roomId';
      path: '/join/$roomId';
      fullPath: '/join/$roomId';
      preLoaderRoute: typeof JoinRoomIdImport;
      parentRoute: typeof rootRoute;
    };
    '/rooms/$roomId': {
      id: '/rooms/$roomId';
      path: '/rooms/$roomId';
      fullPath: '/rooms/$roomId';
      preLoaderRoute: typeof RoomsRoomIdImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/firebase-playground': typeof FirebasePlaygroundRoute;
  '/login': typeof LoginRoute;
  '/sign-up': typeof SignUpRoute;
  '/join/$roomId': typeof JoinRoomIdRoute;
  '/rooms/$roomId': typeof RoomsRoomIdRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/firebase-playground': typeof FirebasePlaygroundRoute;
  '/login': typeof LoginRoute;
  '/sign-up': typeof SignUpRoute;
  '/join/$roomId': typeof JoinRoomIdRoute;
  '/rooms/$roomId': typeof RoomsRoomIdRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/firebase-playground': typeof FirebasePlaygroundRoute;
  '/login': typeof LoginRoute;
  '/sign-up': typeof SignUpRoute;
  '/join/$roomId': typeof JoinRoomIdRoute;
  '/rooms/$roomId': typeof RoomsRoomIdRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/firebase-playground'
    | '/login'
    | '/sign-up'
    | '/join/$roomId'
    | '/rooms/$roomId';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/firebase-playground'
    | '/login'
    | '/sign-up'
    | '/join/$roomId'
    | '/rooms/$roomId';
  id:
    | '__root__'
    | '/'
    | '/firebase-playground'
    | '/login'
    | '/sign-up'
    | '/join/$roomId'
    | '/rooms/$roomId';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  FirebasePlaygroundRoute: typeof FirebasePlaygroundRoute;
  LoginRoute: typeof LoginRoute;
  SignUpRoute: typeof SignUpRoute;
  JoinRoomIdRoute: typeof JoinRoomIdRoute;
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FirebasePlaygroundRoute: FirebasePlaygroundRoute,
  LoginRoute: LoginRoute,
  SignUpRoute: SignUpRoute,
  JoinRoomIdRoute: JoinRoomIdRoute,
  RoomsRoomIdRoute: RoomsRoomIdRoute
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/firebase-playground",
        "/login",
        "/sign-up",
        "/join/$roomId",
        "/rooms/$roomId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/firebase-playground": {
      "filePath": "firebase-playground.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/sign-up": {
      "filePath": "sign-up.tsx"
    },
    "/join/$roomId": {
      "filePath": "join/$roomId.tsx"
    },
    "/rooms/$roomId": {
      "filePath": "rooms/$roomId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
