/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as SignUpImport } from './routes/sign-up';
import { Route as LoginImport } from './routes/login';
import { Route as FirebasePlaygroundImport } from './routes/firebase-playground';
import { Route as IndexImport } from './routes/index';

// Create/Update Routes

const SignUpRoute = SignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute
} as any);

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute
} as any);

const FirebasePlaygroundRoute = FirebasePlaygroundImport.update({
  id: '/firebase-playground',
  path: '/firebase-playground',
  getParentRoute: () => rootRoute
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/firebase-playground': {
      id: '/firebase-playground';
      path: '/firebase-playground';
      fullPath: '/firebase-playground';
      preLoaderRoute: typeof FirebasePlaygroundImport;
      parentRoute: typeof rootRoute;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    '/sign-up': {
      id: '/sign-up';
      path: '/sign-up';
      fullPath: '/sign-up';
      preLoaderRoute: typeof SignUpImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/firebase-playground': typeof FirebasePlaygroundRoute;
  '/login': typeof LoginRoute;
  '/sign-up': typeof SignUpRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/firebase-playground': typeof FirebasePlaygroundRoute;
  '/login': typeof LoginRoute;
  '/sign-up': typeof SignUpRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/firebase-playground': typeof FirebasePlaygroundRoute;
  '/login': typeof LoginRoute;
  '/sign-up': typeof SignUpRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/firebase-playground' | '/login' | '/sign-up';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/firebase-playground' | '/login' | '/sign-up';
  id: '__root__' | '/' | '/firebase-playground' | '/login' | '/sign-up';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  FirebasePlaygroundRoute: typeof FirebasePlaygroundRoute;
  LoginRoute: typeof LoginRoute;
  SignUpRoute: typeof SignUpRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FirebasePlaygroundRoute: FirebasePlaygroundRoute,
  LoginRoute: LoginRoute,
  SignUpRoute: SignUpRoute
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/firebase-playground",
        "/login",
        "/sign-up"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/firebase-playground": {
      "filePath": "firebase-playground.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/sign-up": {
      "filePath": "sign-up.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
